exclude_paths:
  - vendor/
  - public/
  - log/
  - tmp/
  - node_modules/
  - .github/
  - .vscode/
  - .idea/
  - .husky/
  - doc/
  - db/

detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    exclude:
      - API::V1

directories:
  'app/validators':
    UtilityFunction:
      enabled: false
  'spec/support':
    UtilityFunction:
      enabled: false
